name: JSON Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install parse-json and validate json
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: |
          npm install parse-json@5
          node -e "require('parse-json')(require('fs').readFileSync('./kifs.json', 'utf-8'))"
          echo kifs.json is valid

